In [21]:

import pandas as pd
from google.colab import files

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import joblib

In [22]:
uploaded = files.upload()

Saving House_Price_Sheet.xlsx to House_Price_Sheet (2).xlsx

In [23]:
df = pd.read_excel("House_Price_Sheet.xlsx")

display(df.head())

   Area_Sq_Ft  Total_Floors  Bedrooms  Price_Lakhs
0         600             1         1           25
1         750             2         1           30
2         900             1         2           36
3        1050             3         2           42
4        1200             2         2           48

In [24]:

X = df[['Area_Sq_Ft', 'Total_Floors', 'Bedrooms']]

y = df['Price_Lakhs']

display(X.head())
display(y.head())

   Area_Sq_Ft  Total_Floors  Bedrooms
0         600             1         1
1         750             2         1
2         900             1         2
3        1050             3         2
4        1200             2         2

0    25
1    30
2    36
3    42
4    48
Name: Price_Lakhs, dtype: int64

In [25]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [26]:
model = LinearRegression()

model.fit(X_train, y_train)

LinearRegression()

In [27]:
y_pred = model.predict(X_test)

display(y_pred)

array([ 20.48984697, 144.98695054, 141.73846546,  30.46738671])

In [28]:
print("MAE:", mean_absolute_error(y_test, y_pred))

print("MSE:", mean_squared_error(y_test, y_pred))

print("R2 Score:", r2_score(y_test, y_pred))

MAE: 4.432263667993981
MSE: 31.119026843978094
R2 Score: 0.9902728343230967

In [29]:
pred_df = pd.DataFrame({
    'Actual': y_test,
    'Predicted': y_pred
})

display(pred_df)

    Actual   Predicted
0       25   20.489847
17     148  144.986951
15     132  141.738465
1       30   30.467387

In [30]:
new_data = {
    'Area_Sq_Ft': [2000, 3000],
    'Total_Floors': [5, 10],
    'Bedrooms': [3, 4]
}

new_df = pd.DataFrame(new_data)

new_pred = model.predict(new_df)

new_df['Predicted_Price_Lakhs'] = new_pred

display(new_df)

   Area_Sq_Ft  Total_Floors  Bedrooms  Predicted_Price_Lakhs
0        2000             5         3              90.851025
1        3000            10         4             147.731271

In [32]:
joblib.dump(model, "house_price_model1.pkl")

print("Model saved successfully!")

Model saved successfully!

In [33]:
files.download("house_price_model1.pkl")